version: '3.6'
services:
    chinadns-ng:
        image: chinadns-ng
        build: ./
        container_name: chinadns-ng
        restart: unless-stopped
        privileged: true
        network_mode: "host"
        logging: 
            driver: "json-file"
            options: 
                max-size: "10m"
        volumes:
            - ./:/etc/chinadns-ng/
        environment:
            # 监听端口
            PORT: 5353
            # 使用#指定端口，比如114.114.114.114#53
            CHINA_DNS: "114.114.114.114,223.5.5.5" # 国内DNS（最多两组DNS）
            TRUCT_DNS: "202.141.162.123#5353,208.67.222.222#5353" # 可信DNS（最多两组DNS）